const companyDetails = [
  {
    Companyname: 'Acme Corporation',
    Roles: 'Software Engineer, Data Analyst',
    Salary: 4.5,
    Eligibilty: '75%',
    Location: 'Chennai',
    Bound: '12 months',
    Internship: '6 months',
    Deadline: '2023-07-31',
    form: 'https://bit.ly/3g1zq8X',
    users: [
      { name: 'Lelouch Lamperouge', src: 'https://tinyurl.com/4abr7kvf' },
      { name: 'Kurisu Makise', src: 'https://tinyurl.com/33mt89bv' },
      { name: 'Monkey D. Luffy ', src: 'https://tinyurl.com/3p56bmb9' },
      { name: 'Rintaro Okabe', src: 'https://tinyurl.com/45wcucfd' },
      { name: 'Edward Elric', src: 'https://tinyurl.com/2p8awvxn' },
      { name: 'Itachi Uchiha', src: 'https://tinyurl.com/2ynvjhc4' },
      { name: 'Naruto Uzumaki', src: 'https://tinyurl.com/yrr7dnzy' },
      { name: 'Guts', src: 'https://tinyurl.com/bdzjfsfh' },
      { name: 'Gintoki Sakata', src: 'https://tinyurl.com/483k32d3' },
      { name: 'Eren Yeager', src: 'https://tinyurl.com/5bb6txya' },
    ],
  },
  {
    Companyname: 'InnovateTech Solutions',
    Roles: 'Web Developer, UI/UX Designer',
    Salary: 5.5,
    Eligibilty: '70%',
    Location: 'Bangalore',
    Bound: '18 months',
    Internship: '3 months',
    Deadline: '2023-08-15',
    form: 'https://tinyurl.com/m7yxz4p7',
    users: [
      { name: 'Lelouch Lamperouge', src: 'https://tinyurl.com/4abr7kvf' },
      { name: 'Monkey D. Luffy ', src: 'https://tinyurl.com/3p56bmb9' },
      { name: 'Edward Elric', src: 'https://tinyurl.com/2p8awvxn' },
      { name: 'Naruto Uzumaki', src: 'https://tinyurl.com/yrr7dnzy' },
      { name: 'Gintoki Sakata', src: 'https://tinyurl.com/483k32d3' },
    ],
  },
  {
    Companyname: 'Nimbus Systems',
    Roles: 'Software Engineer, Systems Analyst',
    Salary: 6.7,
    Eligibilty: '80%',
    Location: 'Chennai',
    Bound: '24 months',
    Internship: '6 months',
    Deadline: '2023-09-30',
    form: 'https://bit.ly/3g1zq8X',
    users: [
      { name: 'Kurisu Makise', src: 'https://tinyurl.com/33mt89bv' },
      { name: 'Rintaro Okabe', src: 'https://tinyurl.com/45wcucfd' },
      { name: 'Itachi Uchiha', src: 'https://tinyurl.com/2ynvjhc4' },
      { name: 'Gintoki Sakata', src: 'https://tinyurl.com/483k32d3' },
      { name: 'Eren Yeager', src: 'https://tinyurl.com/5bb6txya' },
    ],
  },
  {
    Companyname: 'TechWizards',
    Roles: 'Front-end Developer, UX Researcher',
    Salary: 5.8,
    Eligibilty: '65%',
    Location: 'Bangalore',
    Bound: '12 months',
    Internship: '4 months',
    Deadline: '2023-10-15',
    form: 'https://tinyurl.com/m7yxz4p7',
    users: [
      { name: 'Edward Elric', src: 'https://tinyurl.com/2p8awvxn' },
      { name: 'Eren Yeager', src: 'https://tinyurl.com/5bb6txya' },
      { name: 'Gintoki Sakata', src: 'https://tinyurl.com/483k32d3' },
      { name: 'Guts', src: 'https://tinyurl.com/bdzjfsfh' },
      { name: 'Itachi Uchiha', src: 'https://tinyurl.com/2ynvjhc4' },
      { name: 'Kurisu Makise', src: 'https://tinyurl.com/33mt89bv' },
      { name: 'Lelouch Lamperouge', src: 'https://tinyurl.com/4abr7kvf' },
      { name: 'Monkey D. Luffy ', src: 'https://tinyurl.com/3p56bmb9' },
      { name: 'Naruto Uzumaki', src: 'https://tinyurl.com/yrr7dnzy' },
      { name: 'Rintaro Okabe', src: 'https://tinyurl.com/45wcucfd' },
    ],
  },
  {
    Companyname: 'Innovision Industries',
    Roles: 'Full-stack Developer, Data Scientist',
    Salary: 7.2,
    Eligibilty: '75%',
    Location: 'Chennai',
    Bound: '18 months',
    Internship: '6 months',
    Deadline: '2023-11-30',
    form: 'https://bit.ly/3g1zq8X',
    users: [
      { name: 'Monkey D. Luffy ', src: 'https://tinyurl.com/3p56bmb9' },
      { name: 'Lelouch Lamperouge', src: 'https://tinyurl.com/4abr7kvf' },
      { name: 'Eren Yeager', src: 'https://tinyurl.com/5bb6txya' },
      { name: 'Itachi Uchiha', src: 'https://tinyurl.com/2ynvjhc4' },
      { name: 'Rintaro Okabe', src: 'https://tinyurl.com/45wcucfd' },
      { name: 'Gintoki Sakata', src: 'https://tinyurl.com/483k32d3' },
      { name: 'Naruto Uzumaki', src: 'https://tinyurl.com/yrr7dnzy' },

      { name: 'Edward Elric', src: 'https://tinyurl.com/2p8awvxn' },
      { name: 'Guts', src: 'https://tinyurl.com/bdzjfsfh' },
      { name: 'Kurisu Makise', src: 'https://tinyurl.com/33mt89bv' },
    ],
  },
];
export default companyDetails;
